name: Build Preview

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: dist
      - name: Store pull request number for later use
        run: |
          mkdir -p build/pr
          echo ${{github.event.number}} > build/pr/number
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: build/pr
